

#         Powered by TabooLib 5.0         #


name: 'blockdb'
main: 'ink.ptms.boot.PluginBoot'
version: 'demo'
authors: ['坏黑']

api-version: 1.13

lib-download: true
lib-version: '5.66'
loader-version: '1.2'
